name: Handle /unhold command

on:
  repository_dispatch:
    types: [unhold-command]

jobs:
  handle:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: '${{ github.event.client_payload.github.payload.repository.owner.login }}',
              repo: '${{ github.event.client_payload.github.payload.repository.name }}',
              issue_number: ${{ github.event.client_payload.github.payload.issue.number }},
              name: 'pr-review/hold'
            })
