/**
 * CDP (Chrome DevTools Protocol) Tool Descriptors
 */

import type { ToolDescriptor } from './types'

export const cdpDescriptors: ToolDescriptor[] = [
  {
    canonicalName: 'browser_cdp_connect',
    displayName: 'Browser CDP Connect',
    summary: 'Connect to a Chrome instance via Chrome DevTools Protocol. Establishes a CDP session for browser automation without requiring a browser extension.',
    lane: 'browser_cdp',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_cdp_status',
    displayName: 'Browser CDP Status',
    summary: 'Get the current status of the CDP bridge connection including page URL, title, and connection state.',
    lane: 'browser_cdp',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_cdp_accessibility_snapshot',
    displayName: 'Browser CDP Accessibility Snapshot',
    summary: 'Capture the accessibility tree of the current page via CDP. Returns a hierarchical snapshot of accessible elements.',
    lane: 'browser_cdp',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_cdp_evaluate',
    displayName: 'Browser CDP Evaluate',
    summary: 'Execute JavaScript code in the page context via CDP. Returns the evaluation result.',
    lane: 'browser_cdp',
    kind: 'write',
    readOnly: false,
    destructive: true,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_cdp_collect_elements',
    displayName: 'Browser CDP Collect Elements',
    summary: 'Collect interactive elements from the current page via CDP. Returns a list of clickable, focusable, and input elements with their bounds and attributes.',
    lane: 'browser_cdp',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_cdp_screenshot',
    displayName: 'Browser CDP Screenshot',
    summary: 'Take a screenshot of the current page via CDP. Returns the image in PNG or JPEG format.',
    lane: 'browser_cdp',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_cdp_navigate',
    displayName: 'Browser CDP Navigate',
    summary: 'Navigate the browser to a specified URL via CDP. Waits for the page to load.',
    lane: 'browser_cdp',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
]
