/**
 * Desktop, Terminal, and Browser DOM Tool Descriptors
 *
 * These are the main computer use tools from register-tools.ts
 */

import type { ToolDescriptor } from './types'

export const desktopDescriptors: ToolDescriptor[] = [
  // Desktop observation tools
  {
    canonicalName: 'desktop_get_capabilities',
    displayName: 'Desktop Get Capabilities',
    summary: 'Get system capabilities, preflight checks, and policy configuration. Returns executor type, permissions, display info, and coordinate space details.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_observe_windows',
    displayName: 'Desktop Observe Windows',
    summary: 'List visible windows with optional app name filter. Returns window titles, bounds, and PIDs.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_screenshot',
    displayName: 'Desktop Screenshot',
    summary: 'Capture a screenshot of the current display. Returns the image in base64 format with optional metadata label.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_observe',
    displayName: 'Desktop Observe',
    summary: 'Capture unified desktop observation: screenshot + window list + AX tree + Chrome semantics (when Chrome is foreground). Returns ranked interactable target candidates with ids, bounds, and source labels.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: false,
  },
  {
    canonicalName: 'desktop_click_target',
    displayName: 'Desktop Click Target',
    summary: 'Click on a target candidate from the last desktop_observe snapshot using snap-resolved coordinates (chrome_dom > ax > vision > raw priority). Requires a recent desktop_observe call.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: false,
  },
  {
    canonicalName: 'desktop_ensure_chrome',
    displayName: 'Desktop Ensure Chrome',
    summary: 'Ensure the agent has a dedicated Chrome window. Launches Chrome if not running, creates a new window if already running. Returns session info with PID and CDP URL. Idempotent — repeated calls return the existing session.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: false,
  },

  // Desktop interaction tools
  {
    canonicalName: 'desktop_open_app',
    displayName: 'Desktop Open App',
    summary: 'Open an application. Requires the app to be in COMPUTER_USE_OPENABLE_APPS configuration.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_focus_app',
    displayName: 'Desktop Focus App',
    summary: 'Focus an application window. Requires the app to be in COMPUTER_USE_OPENABLE_APPS configuration.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_click',
    displayName: 'Desktop Click',
    summary: 'Click at global logical screen coordinates, not Retina backing pixels. Supports left/right/middle buttons and click count for double-click.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_type_text',
    displayName: 'Desktop Type Text',
    summary: 'Type text into the focused element. Optionally click at global logical screen coordinates first. Long text (>160 chars) requires approval.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_press_keys',
    displayName: 'Desktop Press Keys',
    summary: 'Press a keyboard shortcut or key combination. Some shortcuts (Cmd+Q, Cmd+Space, etc.) are denied by policy.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_scroll',
    displayName: 'Desktop Scroll',
    summary: 'Scroll the screen at optional global logical screen coordinates. Supports both vertical and horizontal scrolling.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_wait',
    displayName: 'Desktop Wait',
    summary: 'Wait for a specified duration (0-30000ms). Useful for letting UI animations complete.',
    lane: 'desktop',
    kind: 'control',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_get_state',
    displayName: 'Desktop Get State',
    summary: 'Get the current desktop automation state including session status, operation counts, and active context.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: false,
  },
  {
    canonicalName: 'desktop_get_session_trace',
    displayName: 'Desktop Get Session Trace',
    summary: 'Get the session execution trace including all actions taken, timing, and outcomes.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_list_pending_actions',
    displayName: 'Desktop List Pending Actions',
    summary: 'List all actions awaiting approval when running in approval-required mode.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_approve_pending_action',
    displayName: 'Desktop Approve Pending Action',
    summary: 'Approve a pending action by its ID, allowing it to proceed with execution.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'desktop_reject_pending_action',
    displayName: 'Desktop Reject Pending Action',
    summary: 'Reject a pending action by its ID, preventing it from executing.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },

  // Terminal tools
  {
    canonicalName: 'terminal_exec',
    displayName: 'Terminal Exec',
    summary: 'Execute a shell command in the local terminal. Returns stdout, stderr, exit code, and timing. Always requires approval.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: true,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'terminal_reset_state',
    displayName: 'Terminal Reset State',
    summary: 'Reset the terminal state. Clears accumulated command history and state.',
    lane: 'desktop',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'terminal_get_state',
    displayName: 'Terminal Get State',
    summary: 'Get the current terminal execution state including command history and output.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },

  // Browser DOM tools (extension-based)
  {
    canonicalName: 'browser_dom_read_page',
    displayName: 'Browser DOM Read Page',
    summary: 'Read the DOM structure from all frames in the browser via the extension bridge. Returns interactive elements and page structure.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_find_elements',
    displayName: 'Browser DOM Find Elements',
    summary: 'Find elements in the browser DOM matching a selector or role. Returns matching elements with bounds and attributes.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_click',
    displayName: 'Browser DOM Click',
    summary: 'Click a DOM element matching a CSS selector via the browser extension bridge. Works across multiple frames.',
    lane: 'browser_dom',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_check_checkbox',
    displayName: 'Browser DOM Check Checkbox',
    summary: 'Check, uncheck, or toggle a checkbox or radio element via CSS selector in the browser DOM.',
    lane: 'browser_dom',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_set_input_value',
    displayName: 'Browser DOM Set Input Value',
    summary: 'Set the value of an input, select, or textarea element. Optionally simulate keystrokes and blur the element.',
    lane: 'browser_dom',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_select_option',
    displayName: 'Browser DOM Select Option',
    summary: 'Select an option in a select element by value or visible text via the browser extension bridge.',
    lane: 'browser_dom',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_trigger_event',
    displayName: 'Browser DOM Trigger Event',
    summary: 'Dispatch a custom DOM event on an element. Supports multiple event types like click, input, change, and custom events.',
    lane: 'browser_dom',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_read_input_value',
    displayName: 'Browser DOM Read Input Value',
    summary: 'Read the current value of an input, select, or textarea element via CSS selector.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_get_element_attributes',
    displayName: 'Browser DOM Get Element Attributes',
    summary: 'Get all HTML attributes of a DOM element matching the CSS selector.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_get_computed_styles',
    displayName: 'Browser DOM Get Computed Styles',
    summary: 'Retrieve computed CSS styles for an element. Can optionally filter specific CSS properties for layout inspection.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_wait_for_element',
    displayName: 'Browser DOM Wait For Element',
    summary: 'Wait for an element matching a CSS selector to appear in the DOM. Useful for handling async UI updates.',
    lane: 'browser_dom',
    kind: 'control',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_get_active_tab',
    displayName: 'Browser DOM Get Active Tab',
    summary: 'Get the currently active browser tab with title, URL, and metadata.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'browser_dom_get_bridge_status',
    displayName: 'Browser DOM Get Bridge Status',
    summary: 'Get browser DOM bridge connection status including connection state, host, port, and any errors.',
    lane: 'browser_dom',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },

  // Clipboard tools
  {
    canonicalName: 'clipboard_read_text',
    displayName: 'Clipboard Read Text',
    summary: 'Read text content from the system clipboard. Requires approval due to privacy sensitivity.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'clipboard_write_text',
    displayName: 'Clipboard Write Text',
    summary: 'Write text content to the system clipboard. Requires approval due to data sensitivity.',
    lane: 'desktop',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },

  // Secret/env tools
  {
    canonicalName: 'secret_read_env_value',
    displayName: 'Secret Read Env Value',
    summary: 'Read an environment variable value. Requires approval due to potential exposure of secrets.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },

  // Workflow tools
  {
    canonicalName: 'workflow_browse_and_act',
    displayName: 'Workflow Browse And Act',
    summary: 'Execute a workflow to browse to a URL, act on the page, and optionally submit data. Combines navigation and interaction.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'workflow_coding_loop',
    displayName: 'Workflow Coding Loop',
    summary: 'Execute a coding workflow with iterative plan-act-validate-diagnose-recover cycles.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'workflow_coding_agentic_loop',
    displayName: 'Workflow Coding Agentic Loop',
    summary: 'Execute an agentic coding workflow with autonomous decision-making and iteration.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'workflow_open_workspace',
    displayName: 'Workflow Open Workspace',
    summary: 'Open a workspace and validate it is ready for development work.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'workflow_run_tests',
    displayName: 'Workflow Run Tests',
    summary: 'Execute test suite and report results. Handles test failures with diagnostics.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'workflow_validate_workspace',
    displayName: 'Workflow Validate Workspace',
    summary: 'Validate workspace state including dependencies, configuration, and readiness for work.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'workflow_inspect_failure',
    displayName: 'Workflow Inspect Failure',
    summary: 'Inspect and diagnose a test or build failure. Provides root cause analysis and recovery suggestions.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'workflow_resume',
    displayName: 'Workflow Resume',
    summary: 'Resume a suspended workflow from its last checkpoint.',
    lane: 'workflow',
    kind: 'workflow',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'workflow_switch_lane',
    displayName: 'Workflow Switch Lane',
    summary: 'Request a cross-lane handoff (coding → browser, browser → coding, coding → terminal, terminal → coding). Must declare a typed reason and at least one verification constraint. Denied if route is not in the approved allowlist.',
    lane: 'workflow',
    kind: 'control',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
]

/**
 * Internal/test tools (not exposed to MCP clients by default)
 */
export const internalDescriptors: ToolDescriptor[] = [
  {
    canonicalName: 'desktop_open_test_target',
    displayName: 'Desktop Open Test Target',
    summary: 'Open a test target for development/testing purposes. Only available when test tools are enabled.',
    lane: 'internal',
    kind: 'internal',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: false,
    defaultDeferred: true,
  },
]

/**
 * Meta/directory tools
 */
export const metaDescriptors: ToolDescriptor[] = [
  {
    canonicalName: 'tool_directory',
    displayName: 'Tool Directory',
    summary: 'List available tools with optional filtering by lane, kind, or search query. Returns a compact directory for navigation and a structured list for programmatic access.',
    lane: 'internal',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'tool_search',
    displayName: 'Tool Search',
    summary: 'Search tool descriptors by lightweight query and return top ranked candidates without full schema payloads.',
    lane: 'internal',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },

  // Web tools — HTTP-based information gathering without browser surfaces
  {
    canonicalName: 'web_fetch',
    displayName: 'Web Fetch',
    summary: 'Fetch content from a URL via HTTP. Converts HTML to simplified text. No JavaScript execution. For pages requiring login or JS, use browser tools instead.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'web_search',
    displayName: 'Web Search',
    summary: 'Search the web using a query string. Returns a list of result URLs with titles and snippets. Use web_fetch to read full page content.',
    lane: 'desktop',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
]
