/**
 * PTY (Pseudo-Terminal) Tool Descriptors
 */

import type { ToolDescriptor } from './types'

export const ptyDescriptors: ToolDescriptor[] = [
  {
    canonicalName: 'pty_get_status',
    displayName: 'PTY Get Status',
    summary: 'Get the current status of all PTY sessions including their IDs, PIDs, dimensions, and alive states.',
    lane: 'pty',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
  },
  {
    canonicalName: 'pty_create',
    displayName: 'PTY Create',
    summary: 'Create a new PTY session with specified dimensions and working directory. Returns the session ID and PID for subsequent operations.',
    lane: 'pty',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'pty_write',
    displayName: 'PTY Write',
    summary: 'Write raw data to a PTY session. The data is sent directly to the terminal without interpretation.',
    lane: 'pty',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
  },
  {
    canonicalName: 'pty_send_input',
    displayName: 'PTY Send Input',
    summary: 'Send input to a PTY session with optional special key handling (Enter, Ctrl+C, etc.).',
    lane: 'pty',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'pty_read_screen',
    displayName: 'PTY Read Screen',
    summary: 'Read the current screen content from a PTY session. Returns the visible terminal buffer.',
    lane: 'pty',
    kind: 'read',
    readOnly: true,
    destructive: false,
    concurrencySafe: true,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'pty_resize',
    displayName: 'PTY Resize',
    summary: 'Resize a PTY session to new dimensions. Updates the terminal size for proper text wrapping.',
    lane: 'pty',
    kind: 'write',
    readOnly: false,
    destructive: false,
    concurrencySafe: false,
    requiresApprovalByDefault: false,
    public: true,
    defaultDeferred: true,
  },
  {
    canonicalName: 'pty_destroy',
    displayName: 'PTY Destroy',
    summary: 'Destroy a specific PTY session. Terminates the underlying process and releases resources.',
    lane: 'pty',
    kind: 'write',
    readOnly: false,
    destructive: true,
    concurrencySafe: false,
    requiresApprovalByDefault: true,
    public: true,
    defaultDeferred: true,
  },
]
